version: '3.1'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    - MYSQL_DATABASE=${DB_NAME}
    - MYSQL_USER=${DB_USER}
    - MYSQL_PASSWORD=${DB_PASSWORD}
  django:
    image: passonate_django
    restart: always
    env_file:
    - .env
    volumes:
    - ./django_server/entry.sh:/script/entry.sh
    - ./django_server/my.cnf:/etc/mysql/conf.d/my.cnf
    depends_on:
    - mysql
    command: /script/entry.sh
  web:
    image: nginx:alpine
    volumes:
    - ./web_server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - django
