# Generated by Django 3.1 on 2020-09-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssFeedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, blank=True, null=True)),
                ('title', models.TextField()),
                ('link', models.TextField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rss_feed_items',
            },
        ),
        migrations.AddIndex(
            model_name='rssfeeditem',
            index=models.Index(fields=['category'], name='idx_item_category'),
        ),
    ]
